# Generated by Django 5.1.2 on 2024-10-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='detalhes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='descricao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
